Initial scene de Tai-Fighter
PTSD-3D/Tai-Fighter pull request #3
Opened 2021-04-30 19:40 UTC by evalucas

Escena inicial con el prefab de enemy (todavía son kirbys). Para probarla hay que meter a manitas las cosas en Engine.

2021-04-30 21:34 UTC, Pj6595 requested changes
Me peta con este error:

[sol3] An error occurred and panic has been invoked: ./assets/scripts/Client/sampleScene.lua:7: '}' expected (to close '{' at line 5) near 'Components'

Échale un vistazo que puede que se arregle con una cosa que cambió Ricardo esta mañana en el script de exportar la escena

2021-05-02 13:48 UTC, Pj6595 approved these changes
Ya va, guay 👍

2021-05-02 15:11 UTC, EstebenR approved these changes

2021-05-03 09:59 UTC, AdriAlvarez00 requested changes
El eje Z esta cambiado, q salgan las cositas delante para presentarlo bonito mañana

2021-05-03 10:54 UTC, AdriAlvarez00 approved these changes
Danke

2021-05-03 10:54 UTC, merged