Enemigo y Skybox
PTSD-3D/Tai-Fighter pull request #8
Opened 2021-05-12 06:19 UTC by Drathijin

# Lista de cambios
* Cambios en escena para que se vea hacia donde mira la cámara por defecto
* Cambiado el nombre del prefab enemy por player
* Creado nuevo prefab enemy
* Creado componentes y sistemas para el movimiento y la colision de enemigos
* Añadidos archivos .png de skybox y un skybox de galaxia
* Modificaciones al script _build.sh_ para que copie bien los archivos de assets del juego

He decidido dejar separados los sistemas de movimiento y colision con componentes aunque ahora parece trabajo de más para lo poco que hacen. Pero haciéndolo así podemos extender los sistemas y componentes

2021-05-12 08:47 UTC, mmur07 approved these changes
Se ve genial

2021-05-12 10:52 UTC, EstebenR approved these changes

2021-05-12 10:57 UTC, EstebenR requested changes
ahora hay que actualizar los requires :p

2021-05-12 18:57 UTC, EstebenR approved these changes

2021-05-15 12:22 UTC, Adrian-de-Lucas-Gomez approved these changes
El enemigo flota cerca, tenga cuidado soldado. Esto es una puta fantasia.

2021-05-15 12:23 UTC, merged